
# networks: 
#   net:
#     driver: bridge

services:
# docker pull ghcr.io/chroma-core/chroma:0.5.4


  # chroma:
  #   image: 'ghcr.io/chroma-core/chroma:0.5.20'
  #   ports:
  #     - '8000:8000'  
  
  # weaviate:
  #   image: 'semitechnologies/weaviate:latest'
  #   ports:
  #     - '8081:8080'


  # qdrant:
  #   image: 'qdrant/qdrant:latest'
  #   ports:
  #     - '6334:6334'

  # redis:
  #   image: 'redis/redis-stack:latest'
  #   labels:
  #     - "org.springframework.boot.service-connection=redis"
  #   ports:
  #     - '6379:6379'
  
  # rabbitmq:
  #   image: 'rabbitmq:latest'
  #   environment:
  #     - 'RABBITMQ_DEFAULT_PASS=secret'
  #     - 'RABBITMQ_DEFAULT_USER=myuser'
  #   ports:
  #     - '5672:5672'

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'